version: '3.8'

services:
  fhir:
    build: .
    image: fhir_openelis:1.0
    restart: "unless-stopped"
    container_name: fhir_server
    ports:
      - "8021:8080"
    command: /bin/bash -c "/app/scripts/tomcatStart.sh && tail -f /opt/tomcat8/logs/catalina.out"
    depends_on:
      - postgres
    networks:
      - openelis

  postgres:
    container_name: postgres_fhir
    image: postgres:13
    environment:
      POSTGRES_DB: hapi_fhir
      POSTGRES_USER: hapiuser
      POSTGRES_PASSWORD: hapipassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata_fhir:/var/lib/postgresql/data
    networks:
      - openelis

volumes:
  pgdata_fhir:
    driver: local


networks:
  openelis:
    driver: bridge
